// A shape can be defined as a 2D arrayBuffer. Each element represents a brick
// in desired shapes.
// 1 : Brick is presented.
// 0 : Brick is not presented.

/**
 *  * *
 *  * *
 */
export const ShapeO = [
    [1, 1, 0],
    [1, 1, 0],
    [0, 0, 0],
  ];
  
  /**
   *  *
   *  * *
   *    *
   */
  export const ShapeZ = [
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
  ];
  
  /**
   *  *
   *  *
   *  *
   */
  export const ShapeI = [
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
  ];
  
  /**
   *  *
   *  *
   *  * *
   */
  export const ShapeL = [
    [1, 0, 0],
    [1, 0, 0],
    [1, 1, 1],
  ];
  
  /**
   *  * *
   *  * *
   *  * *
   */
  export const ShapeBar = [
    [1, 1, 1],
    [1, 1, 1],
    [0, 0, 0],
  ];
  